Repository rootcodelabs/classifier, pull requests merged in 2024-07, with the labels that each got.

#17 Classifier 97
  DSL/DMapper/hbs/return_jira_issue_info.handlebars
  DSL/DMapper/hbs/return_label_mismatch.handlebars
  DSL/DMapper/hbs/return_outlook_payload_info.handlebars
  DSL/DMapper/hbs/return_platform_response_format.handlebars
  DSL/DMapper/hbs/return_platform_status.handlebars
  DSL/DMapper/lib/helpers.js
  DSL/Liquibase/changelog/create-initial-tables.sql
  DSL/Liquibase/liquibase.properties
  DSL/Liquibase/master.yml
  DSL/Resql/connect-platform.sql
  DSL/Resql/disconnect-platform.sql
  DSL/Resql/get-integration-status.sql
  DSL/Resql/get-jira-input-row-data.sql
  DSL/Resql/get-outlook-input-row-data.sql
  DSL/Resql/get-platform-integration-status.sql
  DSL/Resql/get-token.sql
  DSL/Ruuter.private/DSL/GET/classifier/integration/outlook/token.yml
  DSL/Ruuter.private/DSL/GET/classifier/integration/platform-status.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/jira/cloud/accept.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/jira/cloud/label.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/jira/cloud/subscribe.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/outlook/accept.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/outlook/label.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/outlook/subscribe.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/toggle-platform.yml
  constants.ini
  create-migration.sh
  docker-compose.yml
  migrate.sh
Labels: Backend

#2 Data_Enrichment Module
  src/data_enrichment/Dockerfile
  src/data_enrichment/config_files/paraphraser_config.json
  src/data_enrichment/config_files/translator_config.json
  src/data_enrichment/data_enrichment.py
  src/data_enrichment/data_enrichment_api.py
  src/data_enrichment/paraphraser.py
  src/data_enrichment/requirements.txt
  src/data_enrichment/test_data_enrichment.py
  src/data_enrichment/translator.py
Labels: ML

#22 user-authority: User changes and API Authorization flows
  DSL/Liquibase/changelog/classifier-script-v1-user-management.sql
  DSL/Resql/get-platform-integration-status.sql
  DSL/Ruuter.private/DSL/GET/.guard
  DSL/Ruuter.private/DSL/GET/classifier/integration/outlook/token.yml
  DSL/Ruuter.private/DSL/POST/.guard
  DSL/Ruuter.private/DSL/POST/auth/.guard
  DSL/Ruuter.private/DSL/POST/auth/login.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/outlook/label.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/outlook/subscribe.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/toggle-platform.yml
  DSL/Ruuter.private/DSL/TEMPLATES/check-user-authority.yml
  DSL/Ruuter.public/DSL/POST/auth/login.yml
  DSL/Ruuter.public/DSL/POST/classifier/integration/jira/cloud/accept.yml
  DSL/Ruuter.public/DSL/POST/classifier/integration/outlook/accept.yml
  docker-compose.yml
Labels: Backend

#40 Role Base Access: set role base access to user management and integra…
  DSL/Resql/delete-user.sql
  DSL/Resql/get-users-with-roles-by-role.sql
  DSL/Ruuter.private/DSL/POST/accounts/.guard
  DSL/Ruuter.private/DSL/POST/accounts/users.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/.guard
  DSL/Ruuter.private/DSL/TEMPLATES/check-user-authority-admin.yml
Labels: Backend

#49 ESCLASS-139: integration issue in outlook fixed by setting config and…
  DSL/DMapper/hbs/return_outlook_expiration_date_time.handlebars
  DSL/DMapper/lib/helpers.js
  DSL/Liquibase/changelog/classifier-script-v5-dataset-group-metadata.sql
  DSL/Liquibase/changelog/classifier-script-v5-outlook-refresh-token.xml
  DSL/Ruuter.private/DSL/GET/classifier/integration/outlook/token.yml
  DSL/Ruuter.private/DSL/POST/classifier/integration/outlook/subscribe.yml
  DSL/Ruuter.private/DSL/TEMPLATES/check-user-authority-admin.yml
  constants.ini
  migrate.sh
Labels: Backend, db_update

#50 Microsoft Outlook Consent Application (Dockerization)
  .gitignore
  outlook-consent-app/Dockerfile
  outlook-consent-app/Dockerfile.dev
  outlook-consent-app/docker-compose.yml
  outlook-consent-app/next.config.mjs
  outlook-consent-app/src/app/api/auth/route.ts
  outlook-consent-app/src/app/api/auth/token/route.ts
  outlook-consent-app/src/app/callback/page.tsx
Labels: gui

#51 Feat/ESCLASS-133 : Integration UI API integration
  GUI/src/components/Card/index.tsx
  GUI/src/components/Header/index.tsx
  GUI/src/components/molecules/IntegrationCard/IntegrationCard.scss
  GUI/src/components/molecules/IntegrationCard/index.tsx
  GUI/src/enums/integrationEnums.ts
  GUI/src/enums/roles.ts
  GUI/src/hoc/with-authorization.tsx
  GUI/src/pages/Integrations/index.tsx
  GUI/src/pages/UserManagement/UserModal.tsx
  GUI/src/pages/UserManagement/index.tsx
  GUI/src/services/integration.ts
  GUI/src/store/index.ts
  GUI/src/types/integration.ts
  GUI/src/types/user.ts
  GUI/src/utils/constants.ts
  GUI/translations/en/common.json
Labels: gui, api_integration

#122 Esclass 145 - Node server Implementation And Dataset Progress Session Ruuter API's
  DSL/CronManager/DSL/dataset_progress_session.yml
  DSL/CronManager/script/delete_completed_dataset_progress_sessions.sh
  DSL/DMapper/hbs/return_random_string.handlebars
  DSL/DMapper/lib/helpers.js
  DSL/Liquibase/changelog/classifier-script-v8-dataset-progress-sessions.sql
  DSL/OpenSearch/deploy-opensearch.sh
  DSL/OpenSearch/fieldMappings/dataset_progress_sessions.json
  DSL/OpenSearch/mock/dataset_progress_sessions.json
  DSL/Resql/delete-completed-dataset-progress-sessions.sql
  DSL/Resql/get-dataset-progress-sessions.sql
  DSL/Resql/insert-dataset-progress-session.sql
  DSL/Resql/update-dataset-progress-session.sql
  DSL/Ruuter.private/DSL/GET/classifier/datasetgroup/progress.yml
  DSL/Ruuter.private/DSL/POST/classifier/datasetgroup/progress/create.yml
  DSL/Ruuter.private/DSL/POST/classifier/datasetgroup/progress/delete.yml
  DSL/Ruuter.private/DSL/POST/classifier/datasetgroup/progress/update.yml
  constants.ini
  docker-compose.yml
  notification-server/.env
  notification-server/Dockerfile
  notification-server/index.js
  notification-server/package-lock.json
  notification-server/package.json
  notification-server/src/addOns.js
  notification-server/src/config.js
  notification-server/src/openSearch.js
  notification-server/src/server.js
  notification-server/src/sseUtil.js
Labels: Backend

#123 Bug fixes and improvements in dataset groups
  GUI/.env.development
  GUI/src/components/FormElements/DynamicForm/index.tsx
  GUI/src/components/molecules/ClassHeirarchy/index.tsx
  GUI/src/components/molecules/ValidationCriteria/CardsView.tsx
  GUI/src/components/molecules/ValidationCriteria/RowsView.tsx
  GUI/src/components/molecules/ValidationSessionCard/index.tsx
  GUI/src/enums/commonEnums.ts
  GUI/src/enums/integrationEnums.ts
  GUI/src/pages/DatasetGroups/CreateDatasetGroup.tsx
  GUI/src/pages/DatasetGroups/DatasetGroups.scss
  GUI/src/pages/DatasetGroups/ViewDatasetGroup.tsx
  GUI/src/pages/UserManagement/index.tsx
  GUI/src/pages/ValidationSessions/index.tsx
  GUI/src/services/datasets.ts
  GUI/src/styles/generic/_base.scss
  GUI/src/utils/commonUtilts.ts
  GUI/src/utils/datasetGroupsUtils.ts
  GUI/src/utils/endpoints.ts
  GUI/src/utils/queryKeys.ts
  GUI/translations/en/common.json
  dataset-processor/dataset_processor.py
  docker-compose.yml
Labels: GUI
